### ISSUE TITLE
公共规则管理问题

### ISSUE THREAD

**Issue by dongguangwang** [dianping/camel#13]
公共规则管理里面有前置规则和后置规则，分别做什么用的？ 另外只添加1条公共规则，然后在删除这条规则，会出现无法删除情况。翻了下源代码保存时有如下判断

if (aspects == null || aspects.isEmpty()) {
			return;
}

集合为空不会保存到mongodb里面

**Comment by leonindy** [comment]
nginx配置文件，camel抽象成了公共规则、和路由规则。整个配置文件可以抽象成：
--------
前置规则
路由规则
后置规则
--------

**Comment by dongguangwang** [comment]
好的，多谢。  在    “站点管理-->预览"  按钮下的 nginx的配置文件中， 有如下配置
		set $hcv "-";
		if ( $http_cookie ~* "_hc.v=(\S+)(;.*|$)"){
			set $hcv $1;
		}
		set $dper "-";
		if ( $http_cookie ~* "dper=(\S+)(;.*|$)"){
			set $dper $1;
		}
想问下定义 $hcv ，$dper 这2个变量是用来做什么的。

**Comment by leonindy** [comment]
这个是点评之前sso的逻辑，不影响使用。
你也可以在ftl模板里删除
