### ISSUE TITLE
console控制台是否支持用户名密码登录

### ISSUE THREAD

**Issue by MissingShow** [dianping/camel#14]
你好，软负载中心的console控制台目前是否支持用户名密码方式登录？ 现在camel-admin部署完毕后，直接进入了管理页面。

**Comment by leonindy** [comment]
camel用的是点评内部的权限控制，开源版本已经除去了这部分代码。

建议你自己开发权限管理模块

**Comment by MissingShow** [comment]
好的，谢谢
