### ISSUE TITLE
抱歉，您必须拥有一个终端来执行 sudo

### ISSUE THREAD

**Issue by dongguangwang** [dianping/camel#15]
1. admin/agent节点部署环境tomcat7、jdk7
2. 使用root用户启动admin、agent和 nginx

 
在使用一段时间后（大概1天左右）通过admin控制台发布新版本，agent出现 “抱歉，您必须拥有一个终端来执行 sudo” 问题

具体日志如下：

[2018-03-23 16:28:54.070] [INFO] Getting status from host(10.18.13.144) for deploy(284) ... 
Step: INIT
Progress: 1/7
Step: CHECK_ARGUMENT
Progress: 2/7
Step: BACKUP_OLD_CONFIG
Progress: 3/7
Step: PUT_NEW_CONFIG
Progress: 4/7
Step: RELOAD_OR_DYNAMIC_REFRESH_NGINX
Progress: 5/7
reload tengine config
sudo：抱歉，您必须拥有一个终端来执行 sudo
fail to reload tengine, exit code is 1
Step: ROLL_BACK_CONFIG
Progress: 6/7
Status: failed
Step: FAIL
Progress: 7/7
[2018-03-23 16:28:54.573] [INFO] End deploying with status failed

但是重启后，发布正常

请教下这个是什么问题？

**Comment by leonindy** [comment]
step 5 此处执行脚本文件重启tengine。

是不是sudoer过期了？

**Comment by dongguangwang** [comment]
sudoer 这个过期用什么方法可以看到；目前是用root 启动的，用shell命名测试sudo 可以正常执行的；

**Comment by dongguangwang** [comment]
通过注释掉 /etc/sudoers 文件中的  
`#Defaults    requiretty   `

目前未出现 “抱歉，您必须拥有一个终端来执行 sudo” 的现象
