### ISSUE TITLE
need help see nvm compile 

### ISSUE THREAD

**Issue by donggitdong** [dianping/camel#17]
hello:
I exec nvm clean compile
error input pom file not exit, please fixed it 

**Downloading: http://repo.maven.apache.org/maven2/com/dianping/platform/camel/1.0.0/camel-1.0.0.pom**

[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.dianping.platform:camel-admin:1.0.0 (/data/temp//camel-admin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find com.dianping.platform:camel:pom:1.0.0 in file://${project.basedir}/repo was cached in the local repository, resolution will not be reattempted until the update interval of project-repo has elapsed or updates are forced and 'parent.relativePath' points at

**Comment by wangrangzhi** [comment]
你把对应的maven里面的pom和jar删了重新下载。报错信息说的狠清楚。
