### ISSUE TITLE
agent 部署问题

### ISSUE THREAD

**Issue by zhanshenwan** [dianping/camel#19]
请教一下agent部署问题，我现在部署了，总是提示找不到当前版本,问题如下图：
![image](https://user-images.githubusercontent.com/33242967/39734827-783eebac-52ab-11e8-97c9-52f5735640a8.png)
求教还需要怎么配置？

**Comment by wangrangzhi** [comment]
在站点下面自己写一个.version的文件，然后写上一个数字表示版本，我是看的代码知道这么做的。
但是弄好以后还是无法部署。

**Comment by zhanshenwan** [comment]
研究研究，已经成功部署，感谢。

**Comment by wangrangzhi** [comment]
mongodb版本不对的话就没有办法主动创建.version文件.我后来换了版本就可以主动创建了。

**Comment by gongshenruju** [comment]
请问一下,这个是什么问题?拒绝连接,但是我已经把防火墙关闭了呀
![qq 20180829000317](https://user-images.githubusercontent.com/26380982/44735404-ff931d00-ab1e-11e8-98f5-841975ad3689.png)

**Comment by wangrangzhi** [comment]
你把访问不了的那个url放到浏览器里面看看是什么结果。

**Comment by gongshenruju** [comment]
单独访问那个url时,打不开该url

**Comment by wangrangzhi** [comment]
那说明你的camel-agent那个springboot项目没有启动，理论上说应该是看到一个部署版本的简单的字符串。
