### ISSUE TITLE
不能启动camel-admin，环境为centos7

### ISSUE THREAD

**Issue by mimilong** [dianping/camel#21]
参照word改的，最后结果是war无法被容器启动。启动日志参见附件
[catalina.2018-11-27.log](https://github.com/dianping/camel/files/2620581/catalina.2018-11-27.log)

开始错误如下：
Nov 27, 2018 10:43:09 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultTaskExecutorContainer': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.dianping.phoenix.lb.deploy.service.DeployTaskService com.dianping.phoenix.lb.deploy.executor.DefaultTaskExecutorContainer.deployTaskService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'deployTaskServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.dianping.phoenix.lb.service.model.VirtualServerService com.dianping.phoenix.lb.deploy.service.impl.DeployTaskServiceImpl.virtualServerService; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'virtualServerServiceImpl' defined in file [/var/lib/tomcat/webapps/camel-admin-1.0.0/WEB-INF/classes/com/dianping/phoenix/lb/service/model/VirtualServerServiceImpl.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.dianping.phoenix.lb.dao.VirtualServerDao]: : Error creating bean with name 'virtualServerDaoImpl' defined in file [/var/lib/tomcat/webapps/camel-admin-1.0.0/WEB-INF/classes/com/dianping/phoenix/lb/dao/impl/VirtualServerDaoImpl.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.dianping.phoenix.lb.dao.ModelStore]: : Error creating bean with name 'mongoModelStoreImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.dianping.phoenix.lb.api.dao.AutoIncrementIdGenerator com.dianping.phoenix.lb.dao.mongo.AbstractDbStore.idGenerator; nested exception is

**Comment by leonindy** [comment]
日志没有贴全，root cause应该还在后面，看看最后的nested exception is... 是什么java类。

目前最后一个构建异常是AutoIncrementIdGenerator，初步估计是mongo版本问题
