### ISSUE TITLE
部署繁琐

### ISSUE THREAD

**Issue by mayou33** [dianping/camel#5]
按照你的文档：http://leonindy.coding.me/camel_in_action/
我部署了一下，过程繁琐，要有一定的环境要求，你手册上还没有说。
连接数据库properties文件存放路径不明。
mvn生成war包 后没有能显示页面。
你的 还不如直接给出完好war包呢，我们修改对应的文件就行了。

**Comment by leonindy** [comment]
![image](https://cloud.githubusercontent.com/assets/6918326/19406734/6d4b4988-92be-11e6-96c1-b9588ce85d47.png)

你好，你提到的配置、环境要求，文档里都有提到。
没有出现页面，如果没找到问题可以另开issue并附带详细信息。
