### ISSUE TITLE
调试缺少com.dianping.phoenix.lb.model.entity.*

### ISSUE THREAD

**Issue by lfc3249635** [dianping/camel#8]
你好，调试过程中，发现程序大面积报红，检查发现缺少com.dianping.phoenix.lb.model.entity.*，请问如何处理，谢谢。

**Comment by leonindy** [comment]
你好，这些pojo类是maven插件在compile阶段自动生成的，请按照camel in action中的步骤执行。

**Comment by leonindy** [comment]
FYI
https://github.com/dianping/camel/issues/9
