### ISSUE TITLE
codegen-maven-plugin

### ISSUE THREAD

**Issue by lshm** [dianping/camel#9]
<groupId>org.unidal.maven.plugins</groupId>
                <artifactId>codegen-maven-plugin</artifactId>
                <version>2.1.1</version>
请问一下，这个plugin从哪里可以下载到？

**Comment by leonindy** [comment]
已经包含在camel/camel-admin/repo/org/下了。
这是一个file based依赖。是否你加了maven的全局镜像呢？

**Comment by lshm** [comment]
是不是上传到自己仓库？麻烦给下具体步骤。谢谢

**Comment by leonindy** [comment]
直接mvn compile即可。
如果仍找不到jar包，你可以检查下maven配置：
检查下你的 .m2/settings.xml，是否有全局镜像mirrors，覆盖了camel-admin定义的仓库？
检查下repository是否有超时设置。
maven下载jar包顺序：settings.xml规定仓库->模块指定仓库->父项目指定仓库。
camel-admin在pom中声明仓库如下，相信你一看就明白了：
<repositories>
        <repository>
            <id>project-repo</id>
            <name>project-repo</name>
            <url>file://${project.basedir}/repo</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
</repositories>
